export default {
    NUMBER_ON_CART_IMAGE : '.fa-layers-counter',
    CART_IMAGE : '.fa-shopping-cart',
    SUB_HEADER : '.subheader',
    PRODUCTS_HEADER : '.product_label',
    THE_ABOUT_PAGE_HEADER : '.nav-container',
    MENU_BUTTON : '.bm-burger-button',
    THE_MENU : '.bm-menu',
    CLOSE_MENU : 'Close Menu',
    ALL_ITEMS : '#inventory_sidebar_link',
    ABOUT : '#about_sidebar_link',
    LOG_OUT : '#logout_sidebar_link',
    LOGIN_BUTTON : '#login-button',
    RESET_APP_STATE : '#reset_sidebar_link',
}